config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

 devise_for :admin, skip: [:passwords] ,controllers: {
  sessions: "admin/sessions"
 }

 root to: "public/homes#top"

 #管理者
 namespace :admin do
    root to: "homes#top"

    resources :sessions, only: [:new, :create, :destroy]
    resources :customers
  end

 #会員
 scope module: :public do
  get 'customers/index' => 'customers#index', as:'customers'
  get "customers/show" => "customers#show", as:"customers_my_page"
  get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
  patch 'customers/information' => 'customers#update', as: 'update_customer'
  get "customers/unsubscribe" => "customers#unsubscribe", as:"unsubscribe"
  patch "customers/withdraw" => "customers#withdraw", as:"withdraw"

  resources :animes do
   resource :favorites, only: [:create, :destroy]
   resources :anime_comments, only: [:create, :destroy]
  end

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
   resource :group_customers, only: [:create, :destroy]
   resources :event_notices, only: [:new, :create]
   get "event_notices" => "event_notices#sent"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_one_attached :profile_image
   has_many :animes, dependent: :destroy
   has_many :anime_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :group_customers, dependent: :destroy

   def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
   end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def show
   @customer = Customer.find(params[:id])
   @animes = @customer.animes
  end
  
  def index
   @customers = Customer.all
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<h2><span class="bg-light">会員一覧<span></h2>
 <table class='table'>
  <thead class="table table-light">
   <tr>
    <th>会員ID</th>
    <th>氏名</th>
   </tr>
  </thead>
  <tbody>
   <% @customers.each do |customer| %>
    <tr>
     <td><%= customer.id %></td>
     <td><%= link_to customer.name,admin_customer_path(customer.id) %></td>
    </tr>
   <% end %>
　</tbody>
 </table>
 
 

app/views/admin/customers/show.html.erb
<h2><%=@customer.name %>さんの会員詳細</h2>
 <p>
  <strong class="col-md-3">氏名</strong><%=@customer.name %>
 </p>
 <p>
  <strong class="col-md-3">紹介文</strong><%=@customer.introduction %>
 </p>
 