config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

 devise_for :admin, skip: [:passwords] ,controllers: {
  sessions: "admin/sessions"
 }

 root to: "public/homes#top"

 #管理者
 namespace :admin do
    root to: "homes#top"

    resources :sessions, only: [:new, :create, :destroy]
    resources :customers
  end

 #会員
 scope module: :public do
  get 'customers/index' => 'customers#index', as:'customers'
  get "customers/show" => "customers#show", as:"customers_my_page"
  get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
  patch 'customers/information' => 'customers#update', as: 'update_customer'
  get "customers/unsubscribe" => "customers#unsubscribe", as:"unsubscribe"
  patch "customers/withdraw" => "customers#withdraw", as:"withdraw"

  resources :animes do
   resource :favorites, only: [:create, :destroy]
   resources :anime_comments, only: [:create, :destroy]
  end

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
   resource :group_customers, only: [:create, :destroy]
   resources :event_notices, only: [:new, :create]
   get "event_notices" => "event_notices#sent"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %>件のエラーが発生しました</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title>Animen</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="header">
 <header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container">
    <%= link_to root_path("homes#top") do %>
     <%= image_tag 'wolf-rogo.jpg', size: '100x100', class: "img-fluid" %>
    <% end %>
　<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
   <ul class="nav navbar-nav navbar-right">
    <% if not request.fullpath.include? "admin" %>

    <% if customer_signed_in? %>
     <li class="nav-item">
      <%= link_to '新規投稿', new_anime_path, class: 'nav-link text-light' %>
     </li>
     <li class="nav-item">
      <%= link_to '投稿一覧', animes_path, class: 'nav-link text-light' %>
     </li>
     <li class="nav-item">
      <%= link_to 'ユーザーリスト', customers_path, class: 'nav-link text-light' %>
     </li>
     <li class="nav-item">
      <%= link_to "グループ一覧", groups_path, class: 'nav-link text-light' %>
     </li>

     <li class="nav-item">
      <%= link_to 'マイページ', customers_my_page_path, class: 'nav-link text-light' %>
     </li>
     <li class="nav-item">
      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-light' %>
     </li>

    <% else %>
     <li class="nav-item">
      <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-light' %>
     </li>
     <li class="nav-item">
      <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-light' %>
     </li>
    <% end %>

    <% else %>
    <% if admin_signed_in? %>
     <li class="nav-item">
      <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-light' %>
     </li>
     <li class="nav-item">
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
     </li>
    <% end %>

    <% end %>

    </ul>
   </div>
  </div>
  </nav>
 </header>
 <%= yield %>
 </body>
</html>